export const CHRONIC_CONDITIONS = [
  "diabetes_type_2",
  "hypertension",
  "thyroid_hypothyroidism",
  "thyroid_hyperthyroidism",
  "pcos",
  "high_cholesterol",
  "fatty_liver",
  "acid_reflux",
  "ibs",
  "celiac",
  "anemia",
  "vitamin_d_deficiency",
  "vitamin_b12_deficiency",
  "arthritis",
  "asthma",
  "chronic_kidney_disease",
  "migraine",
  "osteoporosis",
  "gout",
  "insomnia",
  "none",
] as const;

export type ChronicCondition = (typeof CHRONIC_CONDITIONS)[number];

export const CHRONIC_CONDITION_LABELS: Record<ChronicCondition, string> = {
  diabetes_type_2: "Type 2 Diabetes",
  hypertension: "Hypertension",
  thyroid_hypothyroidism: "Hypothyroidism",
  thyroid_hyperthyroidism: "Hyperthyroidism",
  pcos: "PCOS",
  high_cholesterol: "High Cholesterol",
  fatty_liver: "Fatty Liver",
  acid_reflux: "Acid Reflux (GERD)",
  ibs: "IBS",
  celiac: "Celiac Disease",
  anemia: "Anemia",
  vitamin_d_deficiency: "Vitamin D Deficiency",
  vitamin_b12_deficiency: "Vitamin B12 Deficiency",
  arthritis: "Arthritis",
  asthma: "Asthma",
  chronic_kidney_disease: "Chronic Kidney Disease",
  migraine: "Migraine",
  osteoporosis: "Osteoporosis",
  gout: "Gout",
  insomnia: "Insomnia",
  none: "None",
};
